---
title: "Untitled"
output: html_document
---

# GABARITO, NÃO OLHE ISSO DAQUI ANTES DE FAZER O EXERCÍCIO PORQUE SERÁ PIOR PRA VOCÊ


```{r}
# adiciona modelo linear
p1 <- dispersao_escolaridade_x_renda + geom_smooth(aes(color = "a. linear"), method = "lm", formula = y ~ x, se = FALSE, fullrange = TRUE)
p1

# adiciona modelo quadrático
p2 <- p1 + geom_smooth(aes(color = "b. quadratico"), method = "lm", formula = y ~ poly(x, 2), se = FALSE, fullrange = TRUE)
p2

# adiciona modelo de polinômio
p3 <- p2 + geom_smooth(aes(color = "c. erro zero"), method = "lm", formula = y ~ poly(x, 13), se = FALSE, fullrange = TRUE)
p3

p3 + geom_point(data = censo %>% filter(base == "teste"), size = 3, color = "orange")

```


















```{r}

library(tidyverse)
library(forcats)
library(stringr)

# processos <- readRDS("../Aula 1/data/processos_pra_pegar.rds")
# RAW
# d_cjsg <- read_rds("data/d_cjsg.rds") %>% 
#  mutate(n_processo = str_replace_all(n_processo, "[^0-9]", ""))

dataset <- read_rds("../Aula 1/data/d_cposg.rds")

partes <- dataset %>% 
  select(id, parts) %>% 
  unnest(parts) %>% 
  filter(part %in% c("Apelante", "Apelado"), role != "Advogado") %>% 
  # juntar casos com múltiplas partes
  group_by(id, id1, part) %>% 
  summarise(name = paste(name, collapse = "\n")) %>% 
  ungroup() %>%
  # classificacao de tipo de pessoa
  mutate(tipo_part = case_when(
    str_detect(name, "Minist|Justi") ~ "MP",
    TRUE ~ "pessoa"
  )) %>% 
  # em alguns casos, existem pessoas no polo passivo e ativo. 
  # vamos considerar só um (simplificacao)
  distinct(id, part, tipo_part) %>% 
  spread(part, tipo_part) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(apelante)) %>% 
  select(id, autor = apelante)

informacoes <- dataset %>% 
  semi_join(partes, "id") %>% 
  select(id, data) %>% 
  unnest(data) %>% 
  spread(data, value) %>% 
  janitor::clean_names() %>% 
  abjutils::rm_accent_from_names() %>% 
  filter(str_detect(distribuicao, "de Direito Criminal|Extraord")) %>% 
  separate(origem, c("comarca", "foro", "vara"), 
           sep = " / ", extra = "merge", fill = "right") %>% 
  mutate(foro_origem = fct_lump(foro, 10)) %>% 
  separate(assunto, c("assunto_geral", "assunto_intermediario", "assunto"), 
    sep = "-", extra = 'merge', fill = 'right'
  ) %>% 
  mutate_at(vars(assunto, assunto_intermediario), funs(str_trim)) %>% 
  mutate(tipo_camara = if_else(str_detect(distribuicao, "Extra"), 
                               "Extraordinaria", "Ordinaria")) %>% 
  mutate(num_camara = str_extract(distribuicao, "^[0-9]+"),
         num_camara = str_pad(num_camara, 2, "0", side = "left")) %>% 
  select(id, assunto_intermediario, assunto, 
         num_camara, tipo_camara, foro_origem, relator)

tempos <- dataset %>% 
  semi_join(partes, "id") %>% 
  select(id, movs) %>% 
  unnest(movs) %>% 
  filter(movement < Sys.Date(), movement > as.Date("2000-01-01")) %>%
  group_by(id) %>% 
  summarise(n_movs = n(),
            tempo = as.numeric(max(movement) - min(movement)),
            comeco = min(movement),
            idade = Sys.Date() - comeco)

  
# Varias regex
re_vu <- regex("unanim|V\\.? ?U\\.?", ignore_case = TRUE)
re_negaram <- regex("negaram|improc|improv|mantiv|não prov", ignore_case = TRUE)
re_parcial <- regex("parcial|em parte", ignore_case = TRUE)
re_extin <- regex("extin|prejud", ignore_case = TRUE)
re_nulo <- regex("anul|nul[ia]|dilig|conhec", ignore_case = TRUE)
re_deram <- regex("deram|provim|acolher", ignore_case = TRUE)

# todos os tipos de outros
outros <- c("Extinto", "Anul., Dilig., Nao Conhec.", "Outros")

decisoes <- dataset %>% 
  select(id, decisions) %>% 
  unnest(decisions) %>% 
  inner_join(partes, "id") %>% 
  arrange(desc(date)) %>% 
  filter(!is.na(decision)) %>% 
  group_by(id) %>% 
  mutate(num_decision = n()) %>% 
  ungroup() %>% 
  distinct(id, .keep_all = TRUE) %>% 
  mutate(
    unanime = if_else(str_detect(decision, re_vu), "Unanime", "Nao Unanime"),
    decisao = case_when(
      str_detect(decision, re_negaram) & autor == "MP" ~ "Favoravel",
      str_detect(decision, re_negaram) & autor == "pessoa" ~ "Desfavoravel",
      str_detect(decision, re_parcial) ~ "Parcialmente",
      str_detect(decision, re_extin) ~ "Extinto",
      str_detect(decision, re_nulo) ~ "Anul., Dilig., Nao Conhec.",
      str_detect(decision, re_deram) & autor == "MP" ~ "Desfavoravel",
      str_detect(decision, re_deram) & autor == "pessoa" ~ "Favoravel",
      TRUE ~ "Outros"
    ),
    decisao_bin = case_when(
      decisao %in% c("Favoravel", "Parcialmente") ~ "Favoravel",
      (decisao %in% outros & autor == "MP") ~ "Favoravel",
      (decisao %in% outros & autor == "pessoa") ~ "Desfavoravel",
      TRUE ~ "Desfavoravel"
    )
  ) %>% 
  select(id, decisao_bin, decisao, autor, unanime, num_decision)


d_final <- decisoes %>% 
  inner_join(tempos, "id") %>% 
  inner_join(informacoes, "id") %>% 
  distinct(id, .keep_all = TRUE) %>% 
  mutate(decisao_bin = factor(decisao_bin))
```


```{r}
set.seed(10)
treino <- d_final %>% 
  sample_n(15000)
teste <- d_final %>% 
  anti_join(treino, "id")


m <- glm(decisao_bin ~ autor + n_movs + tempo + assunto + 
           num_camara * tipo_camara + foro_origem, 
         data = teste, family = binomial())

m %>% 
  broom::augment(newdata = teste, type.predict = "response") %>% 
  filter(!is.na(.fitted)) %>% 
  mutate(res = if_else(.fitted > .5, "Favoravel", "Desfavoravel")) %>% 
  summarise(prop = sum(res == decisao_bin) / n()) %>% 
  with(prop)

teste %>% 
  count(decisao_bin) %>% 
  mutate(prop = n/sum(n))

saveRDS(d_final, "data/d_final.rds")

```